trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Azure-Service-Connection'
  appName: 'guna-webapp123'
  keyVaultName: 'guna-keyvault'

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(azureSubscription)
    KeyVaultName: $(keyVaultName)
    SecretsFilter: '*'
    RunAsPreJob: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(System.DefaultWorkingDirectory)/**/*.jar'